development:
  adapter: postgresql
  database: sorter_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: sorter_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sorter_production
  pool: 5
  timeout: 5000
